name: Exercise attempt PR opened
run-name: ${{ github.actor }} opened an exercise attempt PR
on:
  pull_request:
    types: [opened]
jobs:
  send-http-request:
    runs-on: ubuntu-latest
    steps:
      - name: Sending Exercise attempt PR opened HTTP request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://eo84zv5pd9vga30.m.pipedream.net'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"repo_url": "${{ github.repositoryUrl }}", "ref_name": "{{ github.ref_name }}"}'
